version: '3.4'

services:
  blogengine:
    image: ${DOCKER_REGISTRY}blogengine
    build:
      context: .
      dockerfile: BlogEngine/Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Today123